baseURL = 'https://ecudemarc.github.io/'
languageCode = 'en-us'
title = 'Écu de Marc'
theme='smol'

# Parameters
[params]
    subtitle = ""
    dateFmt = "02.01.2006 15:04"

# Header
[menu]
  [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 1 

  [[menu.main]]
        identifier = "categories"
        name = "Categories"
        url = "/categories/"
        weight = 2 

  [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 3

# Footer
  [[menu.footer]]
        name = "Github"
        url = "https://github.com/EcuDeMarc/ecudemarc.github.io"
        weight = 1 
